webauthn:
  credential_repository: App\Repository\WebauthnCredentialRepository
  user_repository: App\Repository\WebauthnUserEntityRepository
  allowed_origins:
    - '%env(WEBAUTHN_ORIGIN)%'
  creation_profiles:
    default:
      rp:
        name: '%env(WEBAUTHN_RP_NAME)%'
        id: '%env(WEBAUTHN_RP_ID)%'
      authenticator_selection_criteria:
        resident_key: required
        user_verification: required
  request_profiles:
    default:
      rp_id: '%env(WEBAUTHN_RP_ID)%'
      user_verification: required
  controllers:
    enabled: true
    creation:
      new_user:
        options_path: /inscription/passkey/options
        result_path: /inscription/passkey
        user_entity_guesser: App\Security\RegistrationUserEntityGuesser
    request:
      login:
        options_path: /connexion/passkey/options
