<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260828090812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE a_la_une (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, publication_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_featured_position ON a_la_une (position)');
        $this->addSql('CREATE UNIQUE INDEX uniq_featured_publication ON a_la_une (publication_id)');
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F91ABF038B217A7 ON avis (publication_id)');
        $this->addSql('CREATE INDEX IDX_8F91ABF0A76ED395 ON avis (user_id)');
        $this->addSql('CREATE TABLE langues (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, nom VARCHAR(100) NOT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_119D365977153098 ON langues (code)');
        $this->addSql('CREATE TABLE publications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, titre VARCHAR(255) NOT NULL, contenu TEXT NOT NULL, contenu_format VARCHAR(30) NOT NULL, langue VARCHAR(10) NOT NULL, groupe_traduction_id VARCHAR(36) DEFAULT NULL, statut VARCHAR(20) NOT NULL, source VARCHAR(20) NOT NULL, drive_file_id VARCHAR(255) DEFAULT NULL, nb_likes INT NOT NULL, nb_dislikes INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_32783AF459027487 ON publications (theme_id)');
        $this->addSql('CREATE TABLE reactions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, publication_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_38737FB338B217A7 ON reactions (publication_id)');
        $this->addSql('CREATE INDEX IDX_38737FB3A76ED395 ON reactions (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_publication_user_reaction ON reactions (publication_id, user_id)');
        $this->addSql('CREATE TABLE themes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, slug VARCHAR(180) NOT NULL, icone_fontawesome VARCHAR(100) NOT NULL, ordre INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_154232DE989D9B62 ON themes (slug)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prenom VARCHAR(100) NOT NULL, nom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, code_postal VARCHAR(20) DEFAULT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('ALTER TABLE a_la_une ADD CONSTRAINT FK_7068117F38B217A7 FOREIGN KEY (publication_id) REFERENCES publications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF038B217A7 FOREIGN KEY (publication_id) REFERENCES publications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE publications ADD CONSTRAINT FK_32783AF459027487 FOREIGN KEY (theme_id) REFERENCES themes (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT FK_38737FB338B217A7 FOREIGN KEY (publication_id) REFERENCES publications (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT FK_38737FB3A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE a_la_une DROP CONSTRAINT FK_7068117F38B217A7');
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF038B217A7');
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0A76ED395');
        $this->addSql('ALTER TABLE publications DROP CONSTRAINT FK_32783AF459027487');
        $this->addSql('ALTER TABLE reactions DROP CONSTRAINT FK_38737FB338B217A7');
        $this->addSql('ALTER TABLE reactions DROP CONSTRAINT FK_38737FB3A76ED395');
        $this->addSql('DROP TABLE a_la_une');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE langues');
        $this->addSql('DROP TABLE publications');
        $this->addSql('DROP TABLE reactions');
        $this->addSql('DROP TABLE themes');
        $this->addSql('DROP TABLE users');
    }
}
