parameters:
  app.local_admin_email: '%env(LOCAL_ADMIN_EMAIL)%'
  app.elasticsearch_url: '%env(ELASTICSEARCH_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Service\ElasticsearchService:
    arguments:
      $baseUrl: '%app.elasticsearch_url%'

  App\Command\SeedCommand:
    arguments:
      $kernelEnvironment: '%kernel.environment%'

  App\Security\RegistrationCreationOptionsBuilder:
    arguments:
      $profileBuilder: '@app.webauthn.registration_profile_options_builder'

  app.webauthn.registration_profile_options_builder:
    class: Webauthn\Bundle\CredentialOptionsBuilder\ProfileBasedCreationOptionsBuilder
    arguments:
      $profile: default
